# Generated by Django 4.2.16 on 2026-01-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('CPE', 'CPE Repository'), ('CVE', 'CVE Repository'), ('LINUX', 'Linux CVE Announcements')], max_length=50)),
                ('operation', models.CharField(choices=[('FULL_IMPORT', 'Full Import'), ('INCREMENTAL', 'Incremental Update')], max_length=20)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Success')], max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='core_import_source_3c8099_idx'), models.Index(fields=['created_at'], name='core_import_created_a10b3d_idx')],
            },
        ),
    ]
