# Generated by Django 4.2.16 on 2026-01-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPERecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpe_name', models.CharField(db_index=True, help_text='Full CPE name (e.g., cpe:2.3:a:vendor:product:version:*:*:*:*:*:*:*)', max_length=500, unique=True)),
                ('cpe_name_id', models.CharField(help_text='Unique identifier for this CPE record', max_length=100, unique=True)),
                ('part', models.CharField(help_text="CPE part: 'a' (application), 'o' (operating system), 'h' (hardware)", max_length=1)),
                ('vendor', models.CharField(db_index=True, help_text='Vendor name', max_length=200)),
                ('product', models.CharField(db_index=True, help_text='Product name', max_length=200)),
                ('version', models.CharField(blank=True, help_text='Product version', max_length=100)),
                ('update', models.CharField(blank=True, help_text='Product update', max_length=100)),
                ('edition', models.CharField(blank=True, help_text='Product edition', max_length=100)),
                ('language', models.CharField(blank=True, help_text='Language code', max_length=10)),
                ('sw_edition', models.CharField(blank=True, help_text='Software edition', max_length=100)),
                ('target_sw', models.CharField(blank=True, help_text='Target software', max_length=100)),
                ('target_hw', models.CharField(blank=True, help_text='Target hardware', max_length=100)),
                ('other', models.CharField(blank=True, help_text='Other attributes', max_length=100)),
                ('deprecated', models.BooleanField(db_index=True, default=False, help_text='Whether this CPE is deprecated')),
                ('deprecated_by', models.JSONField(blank=True, help_text='List of CPE names that deprecate this one', null=True)),
            ],
            options={
                'verbose_name': 'CPE Record',
                'verbose_name_plural': 'CPE Records',
                'ordering': ['vendor', 'product', 'version'],
                'indexes': [models.Index(fields=['vendor', 'product'], name='cpe_reposit_vendor_4b1caf_idx'), models.Index(fields=['part', 'vendor'], name='cpe_reposit_part_943708_idx'), models.Index(fields=['deprecated'], name='cpe_reposit_depreca_a5156e_idx'), models.Index(fields=['created_at'], name='cpe_reposit_created_56bcbe_idx')],
            },
        ),
    ]
